languageCode: "en-us"
baseUrl: ""
title: "The Objective"
theme: "hugo-theme-pure"
paginate: 10
disqusShortname: yourdiscussshortname
googleAnalytics: UA-123-45
enableRobotsTXT: true
defaultContentLanguage: zh

# menu:
#   main:
#   - identifier: archive
#     name: Archive
#     title: Archive
#     url: /posts/
#     weight: 0
#   - identifier: About
#     name: About
#     title: About
#     url: /About/
#     weight: 0
menuIcons:
  enable: true  
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

params:
  author: ""
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  customJS:
    - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  readMore: false

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

publishDir : docs